name: Build and Deploy DocFX to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.x'

    - name: Install DocFX
      run: dotnet tool install --global docfx

    - name: Build DocFX site
      run: |
        export PATH="$PATH:~/.dotnet/tools"
        docfx build

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_site  # default output directory for DocFX, adjust if yours is different
